from weibo import Weibo
from qyqq import Qyqq
from github import Github
from redmine import Redmine
from jd import Jd
from gitlab import Gitlab
from amazon import Amazon
from music163 import Music163
from meituan import Meituan
from zhihu import Zhihu
